name: Clean Notebooks

on:
  pull_request:
    paths:
      - '**/*.ipynb'
  push:
    branches: [ main ]
    paths:
      - '**/*.ipynb'

jobs:
  sanitize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run notebook sanitizer
        run: |
          python3 scripts/clean_notebooks.py .
      - name: Check for uncommitted changes
        run: |
          if ! git diff --quiet; then
            echo "Notebook sanitation required. Please run: python3 scripts/clean_notebooks.py . && commit changes."
            echo "Files needing sanitation:" 
            git status --porcelain | awk '$1 ~ /M|A|??/ {print $2}'
            exit 1
          fi


