name: Clean Notebooks

on:
  pull_request:
    paths:
      - '**/*.ipynb'
  push:
    branches: [ main ]
    paths:
      - '**/*.ipynb'

jobs:
  sanitize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run notebook sanitizer
        run: |
          python3 scripts/clean_notebooks.py .
      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add -A
            git commit -m "chore: sanitize notebooks in CI"
            git push
          fi


